### ISSUE TITLE
Logo Proposal for Restreamer

### ISSUE THREAD

**Issue by area55git** [onitake/restreamer#22]
Hi @onitake , I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Restreamer. I could improve the logo you have in the Readme folder.

I will be pleased to collaborate with you.

**Comment by onitake** [comment]
Hi, thanks for your proposal, but I already have a logo designer.
But I'll keep you in mind if I need a logo for a different project.
